import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fa",
  },
  content: {
    padding: 16,
    paddingTop: 50,
    paddingBottom: 32,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 16,
  },
  welcome: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a2e",
    flex: 1,
  },
  logoutBtn: {
    backgroundColor: "#fee2e2",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  logoutText: {
    color: "#991b1b",
    fontWeight: "600",
    fontSize: 14,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1a1a2e",
    marginBottom: 12,
  },
  eventsSection: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 12,
  },
  eventsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 8,
  },
  eventItem: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderStyle: "solid",
  },
  eventType: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1e3a8a",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  eventCourse: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a2e",
  },
  eventTitle: {
    fontSize: 13,
    color: "#374151",
    marginTop: 2,
  },
  eventMeta: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  noEvents: {
    fontSize: 13,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  announcementItem: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  announcementHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  announcementDates: {
    flexDirection: "column",
    gap: 2,
    marginBottom: 6,
  },
  announcementBadge: {
    fontSize: 10,
    fontWeight: "700",
    color: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    overflow: "hidden",
    textTransform: "uppercase",
  },
  announcementTime: {
    fontSize: 11,
    color: "#94a3b8",
  },
  announcementMessage: {
    fontSize: 14,
    color: "#1a1a2e",
    lineHeight: 20,
  },
  announcementAuthor: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 6,
    fontStyle: "italic",
  },
  announcementCourse: {
    fontSize: 12,
    color: "#3b82f6",
    marginTop: 4,
    fontWeight: "600",
  },
});
