import { StyleSheet } from "react-native";

export const materialStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f1f5f9",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 32,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    padding: 32,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: "#64748b",
  },
  errorText: {
    fontSize: 14,
    color: "#ef4444",
    textAlign: "center",
  },
  retryBtn: {
    marginTop: 4,
    backgroundColor: "#1e3a8a",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  retryBtnText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 3,
  },
  emptyContainer: {
    alignItems: "center",
    paddingVertical: 60,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  courseSection: {
    backgroundColor: "#fff",
    borderRadius: 14,
    marginBottom: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  courseHeader: {
    padding: 14,
    gap: 4,
  },
  courseTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  courseCode: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1e3a8a",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  materialCount: {
    backgroundColor: "#eff6ff",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  materialCountText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1e3a8a",
  },
  courseHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  courseName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
    flex: 1,
    marginRight: 8,
  },
  materialList: {
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  materialItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f8fafc",
  },
  materialIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    justifyContent: "center",
    alignItems: "center",
  },
  materialInfo: {
    flex: 1,
    gap: 2,
  },
  materialTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  materialDesc: {
    fontSize: 12,
    color: "#64748b",
    lineHeight: 16,
  },
  materialMeta: {
    fontSize: 11,
    color: "#94a3b8",
    fontWeight: "500",
    marginTop: 2,
  },
  materialActions: {
    flexDirection: "row",
    gap: 4,
  },
  actionBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: "#eff6ff",
    justifyContent: "center",
    alignItems: "center",
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  emptyMaterials: {
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  emptyMaterialsText: {
    fontSize: 13,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  semesterTabs: {
    marginBottom: 16,
  },
  semesterTabsContent: {
    gap: 8,
    paddingRight: 4,
  },
  semesterTab: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  semesterTabActive: {
    backgroundColor: "#1e3a8a",
    borderColor: "#1e3a8a",
  },
  semesterTabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748b",
  },
  semesterTabTextActive: {
    color: "#fff",
  },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 1,
  },
  filterToggleText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1e3a8a",
    flex: 1,
  },
  filterActiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#1e3a8a",
  },
  filterChevron: {
    marginLeft: 2,
  },
  filterPanel: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 14,
    marginBottom: 14,
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 1,
  },
  filterPanelLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  filterChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
  },
  filterChipActive: {
    backgroundColor: "#1e3a8a",
    borderColor: "#1e3a8a",
  },
  filterChipDisabled: {
    opacity: 0.35,
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#475569",
  },
  filterChipTextActive: {
    color: "#fff",
  },
  filterChipTextDisabled: {
    color: "#94a3b8",
  },
});
