import { StyleSheet } from "react-native";

export const scheduleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fa",
  },
  content: {
    padding: 16,
    paddingTop: 50,
    paddingBottom: 32,
  },
  header: {
    marginBottom: 20,
    marginTop: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1a1a2e",
  },
  subtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 2,
  },
  dayTabs: {
    flexDirection: "row",
    marginBottom: 16,
    gap: 6,
  },
  dayTab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#fff",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 4,
    elevation: 1,
  },
  dayTabActive: {
    backgroundColor: "#1e3a8a",
  },
  dayTabLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748b",
    textTransform: "uppercase",
  },
  dayTabLabelActive: {
    color: "#fff",
  },
  dayTabNumber: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a2e",
    marginTop: 2,
  },
  dayTabNumberActive: {
    color: "#fff",
  },
  emptyDay: {
    textAlign: "center",
    color: "#94a3b8",
    fontStyle: "italic",
    fontSize: 14,
    paddingVertical: 32,
  },
  scheduleCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
    borderLeftWidth: 4,
  },
  scheduleTime: {
    fontSize: 13,
    fontWeight: "700",
    color: "#64748b",
    marginBottom: 4,
  },
  scheduleCourse: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1a1a2e",
    marginBottom: 2,
  },
  scheduleType: {
    fontSize: 11,
    fontWeight: "600",
    color: "#fff",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
    alignSelf: "flex-start",
    marginBottom: 6,
  },
  scheduleMeta: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  scheduleLecturer: {
    fontSize: 12,
    color: "#3b82f6",
    marginTop: 4,
    fontWeight: "500",
  },
  buildingLink: {
    fontSize: 12,
    color: "#8b5cf6",
    marginTop: 2,
    fontWeight: "500",
  },
  semesterBadge: {
    backgroundColor: "#eff6ff",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  semesterText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1e3a8a",
  },
  sectionHeader: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
    marginTop: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f7fa",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#64748b",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
    backgroundColor: "#f5f7fa",
  },
  errorText: {
    fontSize: 15,
    color: "#ef4444",
    textAlign: "center",
    marginBottom: 16,
  },
  retryBtn: {
    backgroundColor: "#1e3a8a",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  retryText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
});
